version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - WATCHPACK_POLLING=true
    env_file:
      - .env
    volumes:
      - app_node_modules:/app/node_modules
      - app_next_cache:/app/.next
      - app_prisma:/app/node_modules/.prisma
      - ./:/app:delegated
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: npm run dev

volumes:
  app_node_modules:
  app_next_cache:
  app_prisma:

networks:
  default:
    driver: bridge
