version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: budget_lens_db
      POSTGRES_USER: budget_lens_user
      POSTGRES_PASSWORD: budget_lens_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget_lens_user -d budget_lens_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://budget_lens_user:budget_lens_password@postgres:5432/budget_lens_db?schema=public
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .env:/app/.env

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
